id = "opensow"
name = "OpenSow"
description = "The open source coding agent."
version = "1.1.36"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/opensow"

[agent_servers.opensow]
name = "OpenSow"
icon = "./icons/opensow.svg"

[agent_servers.opensow.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/opensow/releases/download/v1.1.36/opensow-darwin-arm64.zip"
cmd = "./opensow"
args = ["acp"]

[agent_servers.opensow.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/opensow/releases/download/v1.1.36/opensow-darwin-x64.zip"
cmd = "./opensow"
args = ["acp"]

[agent_servers.opensow.targets.linux-aarch64]
archive = "https://github.com/anomalyco/opensow/releases/download/v1.1.36/opensow-linux-arm64.tar.gz"
cmd = "./opensow"
args = ["acp"]

[agent_servers.opensow.targets.linux-x86_64]
archive = "https://github.com/anomalyco/opensow/releases/download/v1.1.36/opensow-linux-x64.tar.gz"
cmd = "./opensow"
args = ["acp"]

[agent_servers.opensow.targets.windows-x86_64]
archive = "https://github.com/anomalyco/opensow/releases/download/v1.1.36/opensow-windows-x64.zip"
cmd = "./opensow.exe"
args = ["acp"]
